version: '3'
services:
  app:
    build: .
    ports:
      - "3000:8080"
    depends_on:
      - redis
      - mysql
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --requirepass 000000
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: s88159868
      MYSQL_DATABASE: videoweb
