// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/cookie"
	handler "videoweb/biz/handler"
	videoweb "videoweb/biz/handler/videoweb"
	router "videoweb/biz/router/videoweb"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	store := cookie.NewStore([]byte("it's_a_secret"))
	r.Use(sessions.New("mysession", store))
	r.GET("/ws", append(router.Chatwebsocket(), videoweb.WebSocket)...)
}
