service:
  AppMode: debug
  HttpPort: ":3000"

redis:
  RedisAddr: 127.0.0.1:6379
  RedisPW: 000000
  RedisDbName: 2

mysql:
  DbHost: 127.0.0.1
  DbPort: 3306
  DbUser: root
  DbPassword: s88159868
  DbName: videoweb

rabbitmq:
  RabbitMqUserName: 102301636
  RabbitMqPassword: 102301636